// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxOBy2TI8q1lKlKVdkoo5-o7w3j0rCx_g',
    appId: '1:508113012020:web:0a9cb6dbcbacded7269161',
    messagingSenderId: '508113012020',
    projectId: 'shoe-kart-e04fd',
    authDomain: 'shoe-kart-e04fd.firebaseapp.com',
    databaseURL: 'https://shoe-kart-e04fd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shoe-kart-e04fd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQOHe2Zm7iaE95nF8zEFC88OTkfkY1BOw',
    appId: '1:508113012020:android:b8e5545ab56e10cc269161',
    messagingSenderId: '508113012020',
    projectId: 'shoe-kart-e04fd',
    databaseURL: 'https://shoe-kart-e04fd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shoe-kart-e04fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeuw-h2tyFUJdwy1RhvqUnKz_wvQwxeXI',
    appId: '1:508113012020:ios:b8320641bb67da79269161',
    messagingSenderId: '508113012020',
    projectId: 'shoe-kart-e04fd',
    databaseURL: 'https://shoe-kart-e04fd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shoe-kart-e04fd.appspot.com',
    iosClientId: '508113012020-snojtquk283ill1ca8n5q76caij82vs3.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminShoeKart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeuw-h2tyFUJdwy1RhvqUnKz_wvQwxeXI',
    appId: '1:508113012020:ios:9601c08a502750e2269161',
    messagingSenderId: '508113012020',
    projectId: 'shoe-kart-e04fd',
    databaseURL: 'https://shoe-kart-e04fd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shoe-kart-e04fd.appspot.com',
    iosClientId: '508113012020-acr9atkfn065v4c0pdt4pp34aq9nt49l.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminShoeKart.RunnerTests',
  );
}
